### ISSUE TITLE
Intercept "hdl:" in Handle names

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2HANDLE/PYHANDLE#25]
Example: 
result = client.retrieve_handle_record_json("hdl:123/456")

This causes an exception because it does not match the expected syntax (index:prefix/suffix). While this is correct, use of the 'hdl:' prefix (or doi:) is sort of legitimate and is also accepted by the main proxies (hdl.handle.net and doi.org). Thus, all methods accepting Handle names should intercept and remove 'hdl:' and 'doi:' before trying an int conversion.

**Comment by merretbuurman** [comment]
Is fixed. Will be in next release.

**Comment by themiszamani** [comment]
It is a duplicate of #49

**Comment by merretbuurman** [comment]
It was not entirely fixed in 2021. The fix back then allowed users to pass handle strings with `hdl:` but did not remove them before sending them to the server's REST API (causing it to respond with http 400 and Response: `{"responseCode":301, "message":"That prefix doesn't live here","handle":"hdl:21.14106/TESTTESTTEST"}`.

Now I fixed that in PR #64 https://github.com/EUDAT-B2HANDLE/PYHANDLE/pull/64 .
